# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 798)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnGuardar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnGuardar.setFont(font)
        self.btnGuardar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnGuardar.setObjectName("btnGuardar")
        self.gridLayout.addWidget(self.btnGuardar, 2, 2, 1, 1)
        self.textResultados = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textResultados.setFont(font)
        self.textResultados.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border: 3px solid black\n"
"")
        self.textResultados.setObjectName("textResultados")
        self.gridLayout.addWidget(self.textResultados, 0, 1, 1, 2)
        self.tablaDatos = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaDatos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 3px solid black;")
        self.tablaDatos.setObjectName("tablaDatos")
        self.tablaDatos.setColumnCount(0)
        self.tablaDatos.setRowCount(0)
        self.gridLayout.addWidget(self.tablaDatos, 0, 0, 1, 1)
        self.btnAnalizar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAnalizar.setFont(font)
        self.btnAnalizar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnAnalizar.setObjectName("btnAnalizar")
        self.gridLayout.addWidget(self.btnAnalizar, 2, 1, 1, 1)
        self.btnCargar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCargar.setFont(font)
        self.btnCargar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnCargar.setObjectName("btnCargar")
        self.gridLayout.addWidget(self.btnCargar, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGuardar.setText(_translate("MainWindow", "Guardar Resultados"))
        self.btnAnalizar.setText(_translate("MainWindow", "Analizar Datos"))
        self.btnCargar.setText(_translate("MainWindow", "Cargar Datos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
